### ISSUE TITLE
PortManager post-release check fails on Windows Server 2012 R2

### ISSUE THREAD

**Issue by cljohnso** [Terracotta-OSS/terracotta-utilities#63]
When used on Windows Server 2012 R2, the port release check performed by `PortManager` fails with an exception of the following form:

```plain
[2022-09-30T13:22:21.704Z] 13:22:21.565 [main] WARN  o.t.u.t.n.PortManager:584 - Unable to obtain busy port information to verify release of port 23210
[2022-09-30T13:22:21.704Z] java.lang.RuntimeException: java.lang.IllegalArgumentException: Error in line - ,"10.130.225.224","23210","10.130.225.224","62810","TimeWait"
[2022-09-30T13:22:21.704Z] 	at org.terracotta.utilities.test.net.NetStat.info(NetStat.java:119)
[2022-09-30T13:22:21.704Z] 	at org.terracotta.utilities.test.net.PortManager.diagnosticReleaseCheck(PortManager.java:566)
[2022-09-30T13:22:21.704Z] 	at org.terracotta.utilities.test.net.PortManager.lambda$combine$6(PortManager.java:755)
[2022-09-30T13:22:21.704Z] 	at org.terracotta.utilities.test.net.PortManager$PortRef.lambda$close$2(PortManager.java:727)
[2022-09-30T13:22:21.704Z] 	at java.util.Optional.ifPresent(Optional.java:159)
[2022-09-30T13:22:21.704Z] 	at org.terracotta.utilities.test.net.PortManager$PortRef.close(PortManager.java:727)
[2022-09-30T13:22:21.704Z] 	at org.terracotta.utilities.test.net.PortManager$PortRef.close(PortManager.java:717)
[2022-09-30T13:22:21.704Z] 	at org.terracotta.angela.common.net.DefaultPortAllocator.close(DefaultPortAllocator.java:71)
... elided ...
[2022-09-30T13:22:21.704Z] Caused by: java.lang.IllegalArgumentException: Error in line - ,"10.130.225.224","23210","10.130.225.224","62810","TimeWait"
[2022-09-30T13:22:21.704Z] 	at org.terracotta.utilities.test.net.NetStat.parseWindowsCsv(NetStat.java:505)
[2022-09-30T13:22:21.704Z] 	at org.terracotta.utilities.test.net.NetStat.access$400(NetStat.java:72)
[2022-09-30T13:22:21.704Z] 	at org.terracotta.utilities.test.net.NetStat$Platform$1.lambda$null$2(NetStat.java:185)
[2022-09-30T13:22:21.704Z] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[2022-09-30T13:22:21.704Z] 	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
[2022-09-30T13:22:21.704Z] 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
[2022-09-30T13:22:21.704Z] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[2022-09-30T13:22:21.704Z] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[2022-09-30T13:22:21.705Z] 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[2022-09-30T13:22:21.705Z] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[2022-09-30T13:22:21.705Z] 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
[2022-09-30T13:22:21.705Z] 	at org.terracotta.utilities.test.net.NetStat$Platform$1.lambda$netstat$3(NetStat.java:185)
[2022-09-30T13:22:21.705Z] 	at org.terracotta.utilities.test.net.NetStat$Platform.runCommand(NetStat.java:413)
[2022-09-30T13:22:21.705Z] 	at org.terracotta.utilities.test.net.NetStat$Platform.access$300(NetStat.java:149)
[2022-09-30T13:22:21.705Z] 	at org.terracotta.utilities.test.net.NetStat$Platform$1.netstat(NetStat.java:186)
[2022-09-30T13:22:21.705Z] 	at org.terracotta.utilities.test.net.NetStat.info(NetStat.java:117)
[2022-09-30T13:22:21.705Z] 	... 28 common frames omitted
[2022-09-30T13:22:21.705Z] Caused by: java.lang.IllegalArgumentException: processId cannot be empty
[2022-09-30T13:22:21.705Z] 	at org.terracotta.utilities.test.net.NetStat$BusyPort$Builder.processId(NetStat.java:1102)
[2022-09-30T13:22:21.705Z] 	at org.terracotta.utilities.test.net.NetStat.parseWindowsCsv(NetStat.java:495)
[2022-09-30T13:22:21.705Z] 	... 43 common frames omitted
```

**Comment by cljohnso** [comment]
Running `org.terracotta.utilities.test.net.NetStat` standalone in Windows Server 2012 R2, yields CSV output that lacks the process id field.

Further exploration revealed the version of PowerShell and CIM/WMI on Windows Server 2012 R2 lacks the `OwningProcess` property in the `Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/MSFT_NetTCPConnection` object returned by `Get-NetTCPConnection` and used by `NetStat`.

Given the age and EOL status of Windows Server 2012 R2, this failure will not be addressed
